name: Build and Deploy WebGL

on:
  push:
    branches:
      - main
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Cache Unity Library
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/unity3d
          ~/.local/share/unity3d
        key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-unity-

    - name: Set Up Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2021.3.17f1
        targetPlatform: WebGL

    - name: Build Project
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: WebGL

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WebGL-Build
        path: Build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: WebGL-Build
        path: ./build/

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          mkdir -p /var/www/Build/
          rsync -avz --delete ./build/ /var/www/Build/
