name: Build and Deploy WebGL

on:
  push:
    branches:
      - main
      - cicd

jobs:
  build:
    name: Build WebGL Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.17f1
          targetPlatform: WebGL

      - name: Build Project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build
          path: Build/  # Adjust this path to match where your WebGL build output is located

  deploy:
    name: Deploy to Web Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download WebGL Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: WebGL-Build
          path: ./build/

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/webgl/
            rsync -avz --delete ./build/ /var/www/webgl/
